# Generated by Django 4.2 on 2023-05-08 14:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("compilerapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="content",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="section",
            name="content",
            field=models.TextField(blank=True, null=True),
        ),
    ]
