# Generated by Django 4.2 on 2023-05-09 09:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("compilerapp", "0002_file_content_alter_section_content"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="catalog",
            name="owner",
        ),
        migrations.RemoveField(
            model_name="file",
            name="owner",
        ),
        migrations.DeleteModel(
            name="User",
        ),
    ]
