# Generated by Django 4.2 on 2023-05-10 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("compilerapp", "0006_catalog_user_file_user_section_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="SectionStatusData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("info", models.TextField(blank=True, null=True)),
                ("info_start_line", models.IntegerField(blank=True, null=True)),
                ("info_end_line", models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=255)),
                ("password", models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name="section",
            name="content",
        ),
        migrations.RemoveField(
            model_name="section",
            name="kind",
        ),
        migrations.RemoveField(
            model_name="section",
            name="parent",
        ),
        migrations.RemoveField(
            model_name="section",
            name="status",
        ),
        migrations.RemoveField(
            model_name="section",
            name="status_data",
        ),
        migrations.AddField(
            model_name="section",
            name="section_status",
            field=models.CharField(
                choices=[("ok", "OK"), ("err", "ERROR"), ("warn", "WARNING")],
                default="ok",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="section",
            name="section_type",
            field=models.CharField(
                choices=[
                    ("prc", "PROCEDURE"),
                    ("cm", "COMMENT"),
                    ("dir", "DIRECTIVES"),
                    ("dec", "DECLARATIONS"),
                    ("as", "ASSEMBLY"),
                ],
                default="prc",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="section",
            name="section_status_data",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="compilerapp.sectionstatusdata",
            ),
        ),
    ]
